import Nav from "@/components/Nav";
import Provider from "@/components/Provider";
import "styles/globals.css";

export const metadata = {
  title: "Next.js-Tutorial",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="main">
            <div className="gradiant" />
          </div>
          <main className="app">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
